// <auto-generated />
using EMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EMS.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20171115163102_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMS.Models.Conhecimento", b =>
                {
                    b.Property<int>("ProgramadorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Android");

                    b.Property<int>("Angular");

                    b.Property<int>("AspNet");

                    b.Property<int>("Bootstrap");

                    b.Property<int>("C");

                    b.Property<int>("CSS");

                    b.Property<int>("Cake");

                    b.Property<int>("Cmais");

                    b.Property<int>("Django");

                    b.Property<int>("HTML");

                    b.Property<int>("IOS");

                    b.Property<int>("Illustrator");

                    b.Property<int>("Ionic");

                    b.Property<int>("Java");

                    b.Property<int>("Jquery");

                    b.Property<int>("Manjento");

                    b.Property<int>("MySql");

                    b.Property<int>("PHP");

                    b.Property<int>("Photoshop");

                    b.Property<int>("Python");

                    b.Property<int>("Ruby");

                    b.Property<int>("SEO");

                    b.Property<int>("SQLServer");

                    b.Property<int>("Salesforce");

                    b.Property<int>("Wordpress");

                    b.HasKey("ProgramadorId");

                    b.ToTable("Conhecimento");
                });

            modelBuilder.Entity("EMS.Models.Conta", b =>
                {
                    b.Property<int>("ProgramadorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Agencia");

                    b.Property<string>("Banco");

                    b.Property<int>("Cpf");

                    b.Property<string>("nomeConta");

                    b.Property<int>("numConta");

                    b.Property<string>("tipoConta");

                    b.HasKey("ProgramadorId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("EMS.Models.Programador", b =>
                {
                    b.Property<int>("ProgramadorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<string>("Disponibilidade");

                    b.Property<string>("Email");

                    b.Property<string>("Estado");

                    b.Property<string>("HorarioTrab");

                    b.Property<string>("Linkedin");

                    b.Property<string>("Nome");

                    b.Property<string>("Portifolio");

                    b.Property<int>("Salario");

                    b.Property<string>("Skype");

                    b.Property<int>("Telefone");

                    b.HasKey("ProgramadorId");

                    b.ToTable("Programador");
                });
#pragma warning restore 612, 618
        }
    }
}
